# ~/.tmuxinator/dev.yml

name: dev
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

windows:
  - chroot: mosh jtrindade@tagus.inesc-id.pt -- schroot -c hardy_amd64 -u jtrindade
  - tagus_qualnet:
       # layout: main-vertical
       layout: 722a,205x58,0,0{126x58,0,0,2,78x58,127,0,6}
       panes:
           - mosh jtrindade@tagus.inesc-id.pt -- zsh -c 'cd workspace/qualnet_map_creator/src; vim; zsh'
           - mosh jtrindade@tagus.inesc-id.pt -- schroot -c hardy_amd64 -u jtrindade
  - tagus_sim: mosh jtrindade@tagus.inesc-id.pt -- zsh -c 'cd workspace/simulator/qualnet/5.0; vim; zsh'
  - phd: cd /home/workspace/phd/
  - spare: #empty
